"""
Generation layer.
Takes a structured AnalysisResult and produces the five context documents
that agents will consume.
Design decisions:
- Documents are Markdown. Agents read Markdown well. Humans can read them too.
- Each document has a defined schema that maps to the analysis models.
- The AGENT_BRIEF is the entry point — it references all others.
- Documents include their own version header so agents know how fresh they are.
- Generation is pure (no I/O) — writing to disk is the caller's responsibility.
"""

from __future__ import annotations

from datetime import UTC, datetime

from .models import AnalysisResult, ContextDocument, ContextDocumentSet

SCHEMA_VERSION = "0.1.0"


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------


def generate(result: AnalysisResult) -> ContextDocumentSet:
    """
    Generate the full set of context documents from an AnalysisResult.

    Args:
        result: The structured analysis from Claude.

    Returns:
        A ContextDocumentSet containing five documents, ready to write to disk.
    """
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    documents = [
        _generate_agent_brief(result, generated_at),
        _generate_architecture(result, generated_at),
        _generate_patterns(result, generated_at),
        _generate_standards(result, generated_at),
        _generate_gaps(result, generated_at),
    ]
    return ContextDocumentSet(
        repo_name=result.repo_name,
        documents=documents,
    )


# ---------------------------------------------------------------------------
# Document generators
# ---------------------------------------------------------------------------


def _header(filename: str, title: str, repo_name: str, generated_at: str) -> str:
    """Standard header for all context documents."""
    return f"""<!--
{filename}
Repository: {repo_name}
Schema version: {SCHEMA_VERSION}
Generated: {generated_at}
This document was generated by Repo Analyser and is intended for AI coding agents.
Do not edit manually — regenerate by running: repo-analyser analyse
-->
# {title}

> **Repository:** `{repo_name}` | **Generated:** {generated_at} | **Schema:** v{SCHEMA_VERSION}

"""


def _generate_agent_brief(result: AnalysisResult, generated_at: str) -> ContextDocument:
    """
    AGENT_BRIEF.md — The entry point. An agent reads this first.
    Contains: what the repo is, critical onboarding notes, and links to other documents.
    """
    lines: list[str] = [
        _header("AGENT_BRIEF.md", "Agent Brief", result.repo_name, generated_at),
    ]
    lines.append("## What This Repository Is\n")
    lines.append(result.summary)
    lines.append("")
    confidence_note = {
        "high": "High confidence — substantial code was available for analysis.",
        "medium": "Medium confidence — analysis is based on a representative sample.",
        "low": (
            "Low confidence — limited code was available. "
            "Treat all observations as provisional."
        ),
    }.get(result.analysis_confidence, "")
    lines.append(f"**Analysis confidence:** {confidence_note}\n")
    if result.analysis_notes:
        lines.append(f"**Analysis caveats:** {result.analysis_notes}\n")
    lines.append("---\n")
    lines.append("## Before You Touch Anything\n")
    lines.append(
        "Read these notes before making any changes. They represent the most critical "
        "things to know about this codebase.\n"
    )
    for note in result.agent_onboarding_notes:
        lines.append(f"- {note}")
    lines.append("")
    high_gaps = [g for g in result.gaps if g.severity == "high"]
    if high_gaps:
        lines.append("---\n")
        lines.append("## High-Severity Gaps — Read Before Coding\n")
        lines.append(
            "These gaps represent known issues in the codebase. "
            "Your instructions for handling them are in `GAPS.md`.\n"
        )
        for gap in high_gaps:
            lines.append(f"- **{gap.title}** — {gap.description}")
        lines.append("")
    lines.append("---\n")
    lines.append("## Context Document Index\n")
    index_rows = [
        "| Document | Contents | When to Read |",
        "|---|---|---|",
        "| `AGENT_BRIEF.md` | This document. Overview and critical notes. | Always, first. |",
        (
            "| `ARCHITECTURE.md` | System structure, components, relationships, "
            "architectural decisions. | Before structural changes. |"
        ),
        (
            "| `PATTERNS.md` | Concrete coding patterns used in this codebase, with examples. "
            "| Before writing new code. |"
        ),
        (
            "| `STANDARDS.md` | Quality standards and what they mean specifically here "
            "(ISO 25010). | When assessing quality or refactors. |"
        ),
        (
            "| `GAPS.md` | Known gaps, inconsistencies, and your instructions for handling them. "
            "| Before risky changes. |"
        ),
    ]
    lines.append("\n".join(row + "\n" for row in index_rows))
    return ContextDocument(
        filename="AGENT_BRIEF.md",
        title="Agent Brief",
        content="\n".join(lines),
    )


def _generate_architecture(result: AnalysisResult, generated_at: str) -> ContextDocument:
    """
    ARCHITECTURE.md — System architecture, aligned with ISO 42010.
    ISO 42010 organises architecture as multiple views, each addressing
    different stakeholder concerns.
    """
    lines: list[str] = [
        _header("ARCHITECTURE.md", "Architecture", result.repo_name, generated_at),
    ]
    lines.append(
        "> This document describes the system architecture aligned with ISO 42010. "
        "Each section represents an architectural viewpoint. Read this before making "
        "structural changes.\n"
    )
    if not result.architectural_views:
        lines.append(
            "_Insufficient code was available to construct architectural views. "
            "Proceed with caution and document any architectural decisions you make._\n"
        )
    else:
        for view in result.architectural_views:
            lines.append(f"## {view.view_name} View\n")
            lines.append(view.description)
            lines.append("")
            if view.key_components:
                lines.append("**Key Components:**\n")
                for component in view.key_components:
                    lines.append(f"- {component}")
                lines.append("")
            if view.relationships:
                lines.append("**Relationships:**\n")
                for rel in view.relationships:
                    lines.append(f"- {rel}")
                lines.append("")
            if view.decisions:
                lines.append("**Architectural Decisions:**\n")
                for decision in view.decisions:
                    lines.append(f"- {decision}")
                lines.append("")
            lines.append("---\n")
    return ContextDocument(
        filename="ARCHITECTURE.md",
        title="Architecture",
        content="\n".join(lines),
    )


def _generate_patterns(result: AnalysisResult, generated_at: str) -> ContextDocument:
    """
    PATTERNS.md — Concrete coding patterns used in this codebase.
    Agents must follow these patterns when writing new code. Examples are
    drawn directly from the codebase.
    """
    lines: list[str] = [
        _header("PATTERNS.md", "Coding Patterns", result.repo_name, generated_at),
    ]
    lines.append(
        "> These are the patterns used in this codebase. When writing new code, "
        "match these patterns. Do not introduce new patterns without a clear reason. "
        "If you deviate, comment why.\n"
    )
    if not result.patterns:
        lines.append(
            "_Insufficient code was available to extract patterns. "
            "Study existing code carefully before introducing new patterns._\n"
        )
    else:
        for i, pattern in enumerate(result.patterns, 1):
            lines.append(f"## {i}. {pattern.name}\n")
            lines.append(pattern.description)
            lines.append("")
            if pattern.example:
                lines.append("**Example from this codebase:**\n")
                lines.append(f"```\n{pattern.example}\n```\n")
            if pattern.locations:
                lines.append("**Found in:**\n")
                for loc in pattern.locations:
                    lines.append(f"- `{loc}`")
                lines.append("")
            if i < len(result.patterns):
                lines.append("---\n")
    return ContextDocument(
        filename="PATTERNS.md",
        title="Coding Patterns",
        content="\n".join(lines),
    )


def _generate_standards(result: AnalysisResult, generated_at: str) -> ContextDocument:
    """
    STANDARDS.md — Quality standards, mapped to ISO 25010.
    ISO 25010 defines software quality characteristics. This document
    describes what each means specifically in this codebase.
    """
    LEVEL_EMOJI = {
        "strong": "🟢",
        "adequate": "🟡",
        "weak": "🟠",
        "absent": "🔴",
        "unknown": "⚪",
    }
    lines: list[str] = [
        _header("STANDARDS.md", "Quality Standards", result.repo_name, generated_at),
    ]
    lines.append(
        "> Quality standards are mapped to ISO 25010. Each characteristic is assessed "
        "against this specific codebase. When writing code, you are expected to maintain "
        "or improve the level shown. Do not regress.\n"
    )
    lines.append("## Quality Summary\n")
    lines.append("| Characteristic | Level | Notes |\n|---|---|---|")
    for qc in result.quality_characteristics:
        emoji = LEVEL_EMOJI.get(qc.observed_level, "⚪")
        short_evidence = qc.evidence[:80] + "..." if len(qc.evidence) > 80 else qc.evidence
        row = (
            f"| {qc.characteristic} | {emoji} {qc.observed_level.title()} | "
            f"{short_evidence} |"
        )
        lines.append(row)
    lines.append("")

    lines.append("---\n")
    lines.append("## Detailed Standards\n")
    for qc in result.quality_characteristics:
        emoji = LEVEL_EMOJI.get(qc.observed_level, "⚪")
        lines.append(f"### {emoji} {qc.characteristic}\n")
        lines.append(f"**Current level:** {qc.observed_level.title()}\n")
        lines.append(f"**Evidence:** {qc.evidence}\n")
        if qc.recommendations:
            lines.append("**Agent instructions:**\n")
            for rec in qc.recommendations:
                lines.append(f"- {rec}")
            lines.append("")
        lines.append("---\n")
    return ContextDocument(
        filename="STANDARDS.md",
        title="Quality Standards",
        content="\n".join(lines),
    )


def _generate_gaps(result: AnalysisResult, generated_at: str) -> ContextDocument:
    """
    GAPS.md — Known gaps, inconsistencies, and agent instructions.
    This document tells agents what is broken, missing, or unclear, and
    what to do about it. It is the most action-oriented document.
    """
    SEVERITY_EMOJI = {"high": "🔴", "medium": "🟠", "low": "🟡"}
    CATEGORY_LABELS = {
        "pattern_inconsistency": "Pattern Inconsistency",
        "missing_documentation": "Missing Documentation",
        "architectural_ambiguity": "Architectural Ambiguity",
        "quality_concern": "Quality Concern",
        "security_concern": "Security Concern",
        "test_coverage": "Test Coverage",
        "dependency_risk": "Dependency Risk",
    }
    lines: list[str] = [
        _header("GAPS.md", "Gaps & Agent Instructions", result.repo_name, generated_at),
    ]
    lines.append(
        "> These are known gaps in the codebase. Each gap includes an instruction "
        "for how an agent should handle it. High-severity gaps must be addressed. "
        "Medium gaps should be addressed if you touch the relevant area. "
        "Low gaps are informational.\n"
    )
    if not result.gaps:
        lines.append(
            "_No gaps detected. This is either a very clean codebase or "
            "analysis coverage was limited._\n"
        )
    else:
        for severity in ["high", "medium", "low"]:
            severity_gaps = [g for g in result.gaps if g.severity == severity]
            if not severity_gaps:
                continue
            emoji = SEVERITY_EMOJI[severity]
            lines.append(f"## {emoji} {severity.title()} Severity\n")
            for gap in severity_gaps:
                category_label = CATEGORY_LABELS.get(gap.category, gap.category)
                lines.append(f"### {gap.title}\n")
                lines.append(f"**Category:** {category_label}")
                lines.append(f"**Description:** {gap.description}\n")
                lines.append(f"**Agent instruction:** {gap.agent_instruction}\n")
                lines.append("---\n")
    return ContextDocument(
        filename="GAPS.md",
        title="Gaps & Agent Instructions",
        content="\n".join(lines),
    )
